version: "3"
services:
  uteam-api:
    container_name: uteam-api
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - uteam-network
    depends_on:
      - uteam-redis
      - uteam-mongo

  uteam-redis:
    image: "redis:alpine"
    ports:
      - "${REDIS_PORT}:6379"
    env_file:
      - .env
    volumes:
      - redis:/data
    networks:
      - uteam-network

  uteam-mongo:
    image: mongo:4.4
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"
    env_file:
      - .env
    networks:
      - uteam-network

  # uteam-mailhog:
  #   image: mailhog/mailhog
  #   logging:
  #     driver: 'none'  # disable saving logs
  #   env_file:
  #     - .env
  #   ports:
  #     - "${MAILHOG_UI_PORT}:8025" # web ui
  #   networks:
  #     - uteam-network

volumes:
  redis:
  mongo:
  node_modules:

networks:
  uteam-network:
    external: false