seed:
	docker-compose run --rm uteam-api npm run seed
setup:
	docker-compose build

install_modules:
	docker-compose run --rm uteam-api npm install

build:
	docker-compose build

stop:
	docker-compose stop

start:
	docker-compose up